import { HOUSEHOLD_VIEW, type FinanceAccount, type FinanceBudget, type FinanceGoal, type FinanceSubscription, type FinanceTransaction } from '@/finance/model'
import { jordan, sam } from '@/prototype/model'

export const FINANCE_CURRENCY = 'USD'

export const seedFinanceAccounts: readonly FinanceAccount[] = [
  {
    id: 'acct-joint-checking',
    name: 'Everyday',
    institution: 'Chase',
    last4: '4242',
    kind: 'checking',
    ownerMembershipId: HOUSEHOLD_VIEW,
    balance: 4820.16,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'acct-joint-savings',
    name: 'Savings',
    institution: 'Chase',
    last4: '1091',
    kind: 'savings',
    ownerMembershipId: HOUSEHOLD_VIEW,
    balance: 6100,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'acct-jordan-checking',
    name: 'Jordan checking',
    institution: 'Ally',
    last4: '7731',
    kind: 'checking',
    ownerMembershipId: jordan.id,
    balance: 1240.55,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'acct-sam-checking',
    name: 'Sam checking',
    institution: 'Ally',
    last4: '2288',
    kind: 'checking',
    ownerMembershipId: sam.id,
    balance: 980.2,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'acct-jordan-card',
    name: 'Sapphire',
    institution: 'Chase',
    last4: '5510',
    kind: 'credit',
    ownerMembershipId: jordan.id,
    balance: -412.33,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'acct-sam-card',
    name: 'Freedom',
    institution: 'Chase',
    last4: '9044',
    kind: 'credit',
    ownerMembershipId: sam.id,
    balance: -188.9,
    currency: FINANCE_CURRENCY,
  },
]

export const seedFinanceTransactions: readonly FinanceTransaction[] = [
  {
    id: 'tx-fairway',
    accountId: 'acct-jordan-card',
    merchant: 'Fairway',
    category: 'Groceries',
    amount: 86.4,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: jordan.id,
    at: '2026-09-05T18:20:00Z',
  },
  {
    id: 'tx-atoboy',
    accountId: 'acct-sam-card',
    merchant: 'Atoboy',
    category: 'Eating out',
    amount: 124,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: sam.id,
    at: '2026-09-03T23:10:00Z',
  },
  {
    id: 'tx-metro',
    accountId: 'acct-joint-checking',
    merchant: 'MTA',
    category: 'Transit',
    amount: 68,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: jordan.id,
    at: '2026-09-01T12:00:00Z',
  },
  {
    id: 'tx-netflix',
    accountId: 'acct-sam-card',
    merchant: 'Netflix',
    category: 'Subscriptions',
    amount: 15.49,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: sam.id,
    at: '2026-09-02T08:00:00Z',
  },
  {
    id: 'tx-nyt',
    accountId: 'acct-jordan-card',
    merchant: 'New York Times',
    category: 'Subscriptions',
    amount: 17,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: jordan.id,
    at: '2026-09-04T08:00:00Z',
  },
  {
    id: 'tx-coned',
    accountId: 'acct-joint-checking',
    merchant: 'Con Edison',
    category: 'Home',
    amount: 94.12,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: jordan.id,
    at: '2026-09-03T14:00:00Z',
  },
  {
    id: 'tx-equinox',
    accountId: 'acct-sam-checking',
    merchant: 'Equinox',
    category: 'Health',
    amount: 210,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: sam.id,
    at: '2026-09-01T07:00:00Z',
  },
  {
    id: 'tx-coffee',
    accountId: 'acct-jordan-card',
    merchant: 'Devoción',
    category: 'Coffee',
    amount: 6.5,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: jordan.id,
    at: '2026-09-06T13:10:00Z',
  },
  {
    id: 'tx-payroll',
    accountId: 'acct-joint-checking',
    merchant: 'Payroll',
    category: 'Income',
    amount: 3200,
    direction: 'in',
    currency: FINANCE_CURRENCY,
    membershipId: jordan.id,
    at: '2026-09-01T15:00:00Z',
  },
  {
    id: 'tx-wine',
    accountId: 'acct-sam-card',
    merchant: 'Chambers Street Wines',
    category: 'Eating out',
    amount: 32,
    direction: 'out',
    currency: FINANCE_CURRENCY,
    membershipId: sam.id,
    at: '2026-08-28T19:00:00Z',
  },
]

export const seedFinanceBudgets: readonly FinanceBudget[] = [
  {
    id: 'bud-groceries',
    name: 'Groceries',
    category: 'Groceries',
    monthlyLimit: 500,
    ownerMembershipId: HOUSEHOLD_VIEW,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'bud-out',
    name: 'Eating out',
    category: 'Eating out',
    monthlyLimit: 250,
    ownerMembershipId: HOUSEHOLD_VIEW,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'bud-transit',
    name: 'Transit',
    category: 'Transit',
    monthlyLimit: 150,
    ownerMembershipId: HOUSEHOLD_VIEW,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'bud-coffee',
    name: 'Coffee',
    category: 'Coffee',
    monthlyLimit: 40,
    ownerMembershipId: jordan.id,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'bud-health',
    name: 'Health',
    category: 'Health',
    monthlyLimit: 250,
    ownerMembershipId: sam.id,
    currency: FINANCE_CURRENCY,
  },
]

export const seedFinanceGoals: readonly FinanceGoal[] = [
  {
    id: 'goal-hudson',
    name: 'Hudson weekend',
    target: 600,
    current: 420,
    ownerMembershipId: HOUSEHOLD_VIEW,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'goal-sofa',
    name: 'New sofa',
    target: 2000,
    current: 350,
    ownerMembershipId: HOUSEHOLD_VIEW,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'goal-camera',
    name: 'Camera',
    target: 1500,
    current: 200,
    ownerMembershipId: jordan.id,
    currency: FINANCE_CURRENCY,
  },
]

export const seedFinanceSubscriptions: readonly FinanceSubscription[] = [
  {
    id: 'sub-netflix',
    name: 'Netflix',
    amount: 15.49,
    cadence: 'monthly',
    nextAt: '2026-10-02T08:00:00Z',
    paidByMembershipId: sam.id,
    ownerMembershipId: HOUSEHOLD_VIEW,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'sub-nyt',
    name: 'New York Times',
    amount: 17,
    cadence: 'monthly',
    nextAt: '2026-10-04T08:00:00Z',
    paidByMembershipId: jordan.id,
    ownerMembershipId: HOUSEHOLD_VIEW,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'sub-coned',
    name: 'Con Edison',
    amount: 94.12,
    cadence: 'monthly',
    nextAt: '2026-10-03T14:00:00Z',
    paidByMembershipId: jordan.id,
    ownerMembershipId: HOUSEHOLD_VIEW,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'sub-equinox',
    name: 'Equinox',
    amount: 210,
    cadence: 'monthly',
    nextAt: '2026-10-01T07:00:00Z',
    paidByMembershipId: sam.id,
    ownerMembershipId: sam.id,
    currency: FINANCE_CURRENCY,
  },
  {
    id: 'sub-icloud',
    name: 'iCloud',
    amount: 2.99,
    cadence: 'monthly',
    nextAt: '2026-09-18T12:00:00Z',
    paidByMembershipId: jordan.id,
    ownerMembershipId: jordan.id,
    currency: FINANCE_CURRENCY,
  },
]
